# Generated by Django 5.2.5 on 2025-09-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
