# Generated by Django 5.2.5 on 2025-09-11 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_questionview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='questionview',
            options={'verbose_name': '질문 조회 기록', 'verbose_name_plural': '질문 조회 기록들'},
        ),
        migrations.AlterUniqueTogether(
            name='questionview',
            unique_together={('question', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'views'], name='pybo_questi_categor_94651d_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-create_date'], name='pybo_questi_create__bb7c10_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-views'], name='pybo_questi_views_2a99bf_idx'),
        ),
        migrations.AddIndex(
            model_name='questionview',
            index=models.Index(fields=['question', 'ip_address'], name='pybo_questi_questio_7c5dde_idx'),
        ),
        migrations.AddIndex(
            model_name='questionview',
            index=models.Index(fields=['created_at'], name='pybo_questi_created_c2f40f_idx'),
        ),
    ]
